export const SET_LOGIN = 'SET_LOGIN';
export const SET_GUEST_USER = 'SET_GUEST_USER';
export const SET_LOGOUT = 'SET_LOGOUT';

export const SET_STARSHIPS = 'SET_STARSHIPS';
export const ERROR_STARSHIPS = 'ERROR_STARSHIPS';
export const SET_PILOT_DETAIL = 'SET_PILOT_DETAIL';
export const ERROR_PILOT_DETAIL = 'ERROR_PILOT_DETAIL';
export const  SET_SEARCH_DIRECTORY = ' SET_SEARCH_DIRECTORY'
